### ISSUE TITLE
override_js error

### ISSUE THREAD

**Issue by PRi0NiTY** [mikeyy/nonoCAPTCHA#22]
title says all

`[shxck@shxck ~]$ python captcha.py 
Traceback (most recent call last):
  File "captcha.py", line 3, in <module>
    from nonocaptcha.solver import Solver
  File "/usr/lib/python3.6/site-packages/nonocaptcha/solver.py", line 16, in <module>
    from nonocaptcha.base import Base, SafePassage
  File "/usr/lib/python3.6/site-packages/nonocaptcha/base.py", line 28, in <module>
    class Base(Clicker):
  File "/usr/lib/python3.6/site-packages/nonocaptcha/base.py", line 42, in Base
    override_data = os.path.join(package_dir, settings["data"]["override_js"])
KeyError: 'override_js'
`

**Comment by mikeyy** [comment]
Thanks for reporting the issue. I forgot to update the example configuration. Can you give the updated example configuration a try?

**Comment by PRi0NiTY** [comment]
`[shxck@shxck examples]$ ls
app.py  app_task.py  nonocaptcha.yaml  proxy.db  run.py  solve.py
[shxck@shxck examples]$ python run.py 
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    from nonocaptcha.solver import Solver
  File "/usr/lib/python3.6/site-packages/nonocaptcha/solver.py", line 14, in <module>
    from nonocaptcha.audio import SolveAudio
  File "/usr/lib/python3.6/site-packages/nonocaptcha/audio.py", line 14, in <module>
    from nonocaptcha.speech import Amazon, Azure, Sphinx, DeepSpeech
  File "/usr/lib/python3.6/site-packages/nonocaptcha/speech.py", line 22, in <module>
    from nonocaptcha import settings
ImportError: cannot import name 'settings'
`

**Comment by mikeyy** [comment]
Complete oversight on my part. The latest update should fix everything now. 👍
