### ISSUE TITLE
FastChildWatcher

### ISSUE THREAD

**Issue by ThisIsMohsen** [mikeyy/nonoCAPTCHA#38]
hi im using python 3.7.1 on windows x64 Server 2008.
but i got this error : 

C:\Users\Administrator\Desktop\nonoCAPTCHA-master\examples>python app.py
Traceback (most recent call last):
  File "app.py", line 39, in <module>
    asyncio.set_child_watcher(asyncio.FastChildWatcher())
AttributeError: module 'asyncio' has no attribute 'FastChildWatcher'

C:\Users\Administrator\Desktop\nonoCAPTCHA-master\examples>

what is my problem ?
thanks

**Comment by mikeyy** [comment]
Sorry for the delay. Can you try the updated example file app.py?

**Comment by Msmyli** [comment]
thanks for answer
but i have same problem :

C:\Users\Administrator\Desktop\nonoCAPTCHA-master\examples>python app.py
Traceback (most recent call last):
  File "app.py", line 40, in <module>
    asyncio.set_child_watcher(asyncio.SafeChildWatcher())
AttributeError: module 'asyncio' has no attribute 'SafeChildWatcher'

C:\Users\Administrator\Desktop\nonoCAPTCHA-master\examples>

**Comment by mikeyy** [comment]
Try now

**Comment by mikeyy** [comment]
Latest update worked on my Windows virtual machine.
