### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by unlimitedcoder2** [mikeyy/nonoCAPTCHA#41]
import asyncio
from nonocaptcha.solver import Solver

pageurl = ''
sitekey = ''

args = ["--timeout 5"]
options = {"ignoreHTTPSErrors": True, "args": args}
client = Solver(
	pageurl,
	sitekey,
	options=options
)

solution = asyncio.get_event_loop().run_until_complete(client.start())

if solution:
	print(solution)

root@MumblePVP:~/c9launcher/workspaces/chatroom-dev/Bloxility# python3 recapBypass.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nonocaptcha-1.8.8-py3.8.egg/nonocaptcha/solver.py", line 54, in start
    self.browser = await self.get_new_browser()
  File "/usr/local/lib/python3.8/site-packages/nonocaptcha-1.8.8-py3.8.egg/nonocaptcha/solver.py", line 143, in get_new_browser
    browser = await self.launcher.launch()
  File "/usr/local/lib/python3.8/site-packages/nonocaptcha-1.8.8-py3.8.egg/nonocaptcha/launcher.py", line 72, in launch
    self.browserWSEndpoint = await self._get_ws_endpoint()
  File "/usr/local/lib/python3.8/site-packages/nonocaptcha-1.8.8-py3.8.egg/nonocaptcha/launcher.py", line 91, in _get_ws_endpoint
    await self.proc.stdout.read().decode()
AttributeError: 'NoneType' object has no attribute 'read'

2018-11-19 09:50:27,031 0 'NoneType' object has no attribute 'read' <class 'AttributeError'>
2018-11-19 09:50:27,031 0 Time elapsed: 0.23222041130065918
root@MumblePVP:~/c9launcher/workspaces/chatroom-dev/Bloxility# 

Whenever running the code above I get this error. I am using python 3 ( pip 10.0.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8) )

**Comment by unlimitedcoder2** [comment]
Forgot to mention this in my post but I am using azure

**Comment by mikeyy** [comment]
If you are lacking a gui environment, make sure you've set the headless setting to _True_.

**Comment by unlimitedcoder2** [comment]
Thanks changing headless to true fix the issue
