### ISSUE TITLE
Google Chrome Error: "Automated Queries"

### ISSUE THREAD

**Issue by articlefr** [mikeyy/nonoCAPTCHA#42]
I have been getting these errors upon clicking the audio button image. 

The error is an automated error: "Your computer or network may be sending automated queries. To protect our users, we can't process your request right now." 

Please help.,

**Comment by jerryan999** [comment]
same like you

**Comment by drevie** [comment]
Getting the same response.

**Comment by articlefr** [comment]
I have a very rough idea... I have tried using operadriver on top of chromedriver. And what I did is to bypass the deface function. Meaning I did not deface the pages... and it worked... 

Conclusion: Google flags you as a bot if you deface the page and single out the captcha. Perhaps this can be adjusted in nonoCAPTCHA package...

Thanks!

**Comment by mikeyy** [comment]
Thanks for the detailed information. I will attempt to run some test in the next few days.

**Comment by jboadas** [comment]
> I have a very rough idea... I have tried using operadriver on top of chromedriver. And what I did is to bypass the deface function. Meaning I did not deface the pages... and it worked...
> 
> Conclusion: Google flags you as a bot if you deface the page and single out the captcha. Perhaps this can be adjusted in nonoCAPTCHA package...
> 
> Thanks!

Hello, how do you achieve this? 
I mean, avoid deface and use chromedriver and operadriver together.
Thanks

**Comment by mikeyy** [comment]
I've added an option to disable defacing of the page, simply pass along enable_deface=False as parameter to Solver.

For example:

```python
client = Solver(pageurl, sitekey, options=options, proxy=proxy, enable_deface=False)
try:
    result = loop.run_until_complete(client.start())
except asyncio.CancelledError:
    raise
else:
    if result:
        print(result)
```

**Notice** This will not work if the reCAPTCHA widget is not initially loaded onto the page, the iframe must already be loaded and not triggered from a button click event or of the likes.

**Comment by mikeyy** [comment]
Modification to the config file is necessary as well, replace deface under timeouts with iframe.

**Comment by mikeyy** [comment]
To clarify, this isn't a solution to the above problem but an option until I can get around to circumventing their method for detecting the document overwrite.

**Comment by jboadas** [comment]
Thanks I will try

**Comment by mikeyy** [comment]
Latest update intercepts the request to the set page and replaces it with the deface code, instead of the previous method of using DOM manipulation through JavaScript injecting the widget.

An optional setting for retaining the source code of the page being requested is also available as a parameter on Solver. Problems could arise if the page already has a reCAPTCHA widget or if a _</body>_ tag is non-existent.

Feedback is welcomed, and encouraged for those previously experiencing issues from the earlier method.

**Comment by mikeyy** [comment]
Latest update appears to be a working solution on my end, I'm closing this issue and marking it as resolved.

**Comment by AlessandroSpallina** [comment]
i continue to see the issue and in command line i get this:

`$ python3 demo.py
2018-12-25 17:40:35,098 0 Starting solver with proxy http://xxxxxx:53281
2018-12-25 17:40:49,151 0 Clicking checkbox
2018-12-25 17:40:54,394 0 Clicking audio button
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 74, in start
    result = await self.solve()
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 275, in solve
    return await self._solve()
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 310, in _solve
    result = await self.loop.create_task(solve())
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/audio.py", line 34, in solve_by_audio
    self.get_audio_response())
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/audio.py", line 60, in get_audio_response
    raise DownloadError("Audio url is not valid, aborting")
nonocaptcha.exceptions.DownloadError: Audio url is not valid, aborting

2018-12-25 17:40:59,875 0 Audio url is not valid, aborting <class 'nonocaptcha.exceptions.DownloadError'>
2018-12-25 17:41:00,358 0 Browser closed
2018-12-25 17:41:00,358 0 Time elapsed: 26.60468864440918`

**Comment by jboadas** [comment]
I still get this "automated queries" error and the script is "detected"

2018-12-25 12:32:54,041 0 Result: Detected
2018-12-25 12:32:54,825 0 Browser closed
2018-12-25 12:32:54,825 0 Time elapsed: 19.28381037712097
{'status': 'detected'}

**Comment by mikeyy** [comment]
> yes I am doing some automated tests to https://www.coinimp.com/login

Thanks. Same detected result on my end. I will continue to test with this page to see if I can produce some magic.

**Comment by mikeyy** [comment]
@AlessandroSpallina This is a separate issue. Fortunately, it seems I was able to reproduce it on my end. I will make a new post for this issue so we can continue searching for a resolve.

**Comment by mikeyy** [comment]
@jboadas I've tested with multiple proxies and I can't even access the audio part manually with Chromium, Chrome, or Firefox on the provided address. Can you try manually accessing the audio part on your end? Make sure you aren't logged into a Google account since this likely will succeed with a 1-click.

**Comment by articlefr** [comment]
My app.py
still stops at
2018-12-25 10:19:49,673 0 Time elapsed: 22.136663913726807
2018-12-25 10:19:51,299 1 Starting solver with proxy None
2018-12-25 10:19:58,797 1 Clicking checkbox
2018-12-25 10:20:03,993 1 Clicking audio button
2018-12-25 10:20:09,856 1 Downloading audio file

**Comment by AlessandroSpallina** [comment]
if i follow you last post @mikeyy i don't get any output
