### ISSUE TITLE
Error "Audio url is not valid, aborting"

### ISSUE THREAD

**Issue by mikeyy** [mikeyy/nonoCAPTCHA#45]
i continue to see the issue and in command line i get this:

`$ python3 demo.py
2018-12-25 17:40:35,098 0 Starting solver with proxy http://xxxxxx:53281
2018-12-25 17:40:49,151 0 Clicking checkbox
2018-12-25 17:40:54,394 0 Clicking audio button
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 74, in start
    result = await self.solve()
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 275, in solve
    return await self._solve()
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 310, in _solve
    result = await self.loop.create_task(solve())
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/audio.py", line 34, in solve_by_audio
    self.get_audio_response())
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/audio.py", line 60, in get_audio_response
    raise DownloadError("Audio url is not valid, aborting")
nonocaptcha.exceptions.DownloadError: Audio url is not valid, aborting

2018-12-25 17:40:59,875 0 Audio url is not valid, aborting <class 'nonocaptcha.exceptions.DownloadError'>
2018-12-25 17:41:00,358 0 Browser closed
2018-12-25 17:41:00,358 0 Time elapsed: 26.60468864440918`

how to fix that?

_Originally posted by @AlessandroSpallina in https://github.com/mikeyy/nonoCAPTCHA/issues/42#issuecomment-449862374_

**Comment by mikeyy** [comment]
@AlessandroSpallina Can you confirm that the click misfires, clicking one of the image tiles instead of the audio button? You will notice one of the images fade out with a green check mark overlaying the tile.

**Comment by AlessandroSpallina** [comment]
No, i think the issue is related to Amazon and azure api key missing in my config file, my fault.
Both Amazon and azure are mandatory, right?

**Comment by mikeyy** [comment]
You are free to choose between the 4 available speech services. By default the service is Pocketsphinx.

This requires the language model files located here - https://github.com/cmusphinx/pocketsphinx/tree/master/model. Save them inside the same directory as the configuration file and modify the destination at the following `model_dir` line. Personally, I use `pocketsphinx/model` for Pocketsphinx and `deepspeech/models` for Deepspeech. Both Deepspeech and Pocketsphinx run locally. 

```
pocketsphinx:
        model_dir:
```

While Azure and Amazon are a more convenient option, they are financially impractical for extensive testing. Reason being it costs more per 1000 speech-to-text calls compared to using a third party captcha solving service. Lastly, Amazon on average takes up to a minute for processing a request and Azure is exceptionally faster with a response time no more than 15 seconds.

I plan on outlining the requirements and install process in detail sometime in the future.

**Comment by AlessandroSpallina** [comment]
thanks for the support.
i cloned the pocketsphinx in /example directory, i removed the proxy settings (but nothing change if i use a free proxy found online) in demo.py and try to run the script with python3.6. It seemed to work.. instead to have the #42 issue displayed in chromium and at the same time in my terminal <Error "Audio url is not valid, aborting"> i get the menu of the audio, but the script end without downloading anything...
After some tests, for no reason, now i have again the #42 issue in the browser and the error audio url

**Comment by AlessandroSpallina** [comment]
the output now is longer
`$ python3.6 demo.py 
2018-12-25 23:50:21,080 0 Starting solver with proxy http://171.100.2.154:8080
2018-12-25 23:50:21,965 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 108, in handle_request
    'body': source
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 513, in respond
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:23,712 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:23,714 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:24,128 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:25,460 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:25,870 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:26,247 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:26,698 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:27,962 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:28,018 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:28,050 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:28,064 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:28,587 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:29,007 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:29,330 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:29,358 0 Clicking checkbox
2018-12-25 23:50:30,786 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,614 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,616 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,619 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,621 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,632 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,661 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,675 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,766 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:31,821 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:34,492 0 Clicking audio button
2018-12-25 23:50:34,953 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
2018-12-25 23:50:36,261 Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...y handled.',)>) at /usr/local/lib/python3.6/site-packages/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/site-packages/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 111, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 74, in start
    result = await self.solve()
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 275, in solve
    return await self._solve()
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/solver.py", line 310, in _solve
    result = await self.loop.create_task(solve())
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/audio.py", line 34, in solve_by_audio
    self.get_audio_response())
  File "/usr/local/lib/python3.6/site-packages/nonocaptcha/audio.py", line 60, in get_audio_response
    raise DownloadError("Audio url is not valid, aborting")
nonocaptcha.exceptions.DownloadError: Audio url is not valid, aborting

2018-12-25 23:50:39,973 0 Audio url is not valid, aborting <class 'nonocaptcha.exceptions.DownloadError'>
2018-12-25 23:50:40,482 0 Browser closed
2018-12-25 23:50:40,483 0 Time elapsed: 20.937331914901733
`

**Comment by AlessandroSpallina** [comment]
so, test_speech.py located in the root directory of the project not produce any output.
I use ubuntu 18.04 with python3, all my dependecies are in the right version.
Now, i run the script in example/demo.py with [this config in example/nonocaptcha.yaml](https://arin.ga/zg74wT), i run demo.py without proxy, [here the code](https://arin.ga/Pm32mm).
I get different behavior if i run the script many times, i get 3 different behaviour:
1) #42 issue and nothing to do, sometimes this is fixed if i  change animation timeout in config file, but after 1 or 2 change this "fix" doesn't work anymore.
2) [this output](https://arin.ga/jXbUqQ), very fast opening chromium and closing without any real action
3) a lock situation "audio url invalid", follow a screen of my browser
![schermata del 2018-12-26 16-03-39](https://user-images.githubusercontent.com/10786872/50450193-94baec80-092c-11e9-842f-bbf32de55596.png)
and this is the output in my [terminal ](https://arin.ga/nDIIpg)

this is frustrating, i think the best way is try to set all the environment in a fresh ubuntu installation and write a full detailed guide and consider that doc "the way"

**Comment by soultobleed** [comment]
I'm having the same issue, not sure why, yet. 
It seems to be failing when it tries to download a couple of payloads. 
![image](https://user-images.githubusercontent.com/2480975/51679589-7517f200-1fc6-11e9-911e-20017afecedf.png)

**Comment by mikeyy** [comment]
Unfortunately, I'm lacking funds to actually pursue any further developments. It is my deepest regret to announce that until then this project's future is at a full-stop.
