### ISSUE TITLE
client.start() NotImplementedError

### ISSUE THREAD

**Issue by Hristijan95** [mikeyy/nonoCAPTCHA#46]
Hello,

I am getting the following error when trying to run the library:

> Traceback (most recent call last):
2018-12-29 15:37:53,698 0  <class 'NotImplementedError'>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonocaptcha\solver.py", line 62, in start
2018-12-29 15:37:53,698 0 Time elapsed: 0.01298832893371582
    self.browser = await self.get_new_browser()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonocaptcha\solver.py", line 183, in get_new_browser
    browser = await self.launcher.launch()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonocaptcha\launcher.py", line 69, in launch
    env=env,
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1522, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 452, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

It seems that the problem is that the library is not able to open my browser, but I don't know what is causing this.

**Comment by mikeyy** [comment]
Hello,

Sorry for the lengthy delay in providing a response. It would appear you are using the incorrect event loop.

On Windows, use the Protractor event loop. For example. replacing the following:
```python
loop = asyncio.get_event_loop()
```
with

```python
loop = asyncio.ProactorEventLoop()
asyncio.set_event_loop(loop)
```
