### ISSUE TITLE
headlesss dont work properly!

### ISSUE THREAD

**Issue by MacKey-255** [mikeyy/nonoCAPTCHA#55]
Hi, I was testing your code and it works perfectly with GUI, try to test it on a server without a GUI & the headless = True and this expels the following error.
Data:
- Python 3.7.2
- OS Linux (Debian 9)

My code:
```
import asyncio
from nonocaptcha.solver import Solver

pageurl = "page"
sitekey = "sitekey"

args = ['--no-sandbox', '--user-data-dir', '--timeout 15', '--disable-setuid-sandbox']
options = {"ignoreHTTPSErrors": True, "args": args}
client = Solver(
    pageurl, sitekey, options=options, proxy=None, proxy_auth=None)

solution = asyncio.get_event_loop().run_until_complete(client.start())
if solution:
    print(solution)
```
Output:
```
var/www/project_test/nonocaptcha/base.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  settings = yaml.load(f)
headless is True
Traceback (most recent call last):
  File "/var/www/project_test/nonocaptcha/solver.py", line 62, in start
    self.browser = await self.get_new_browser()
  File "/var/www/project_test/nonocaptcha/solver.py", line 190, in get_new_browser
    browser = await self.launcher.launch()
  File "/var/www/project_test/nonocaptcha/launcher.py", line 75, in launch
    self.browserWSEndpoint = await self._get_ws_endpoint()
  File "/var/www/project_test/nonocaptcha/launcher.py", line 94, in _get_ws_endpoint
    await self.proc.stdout.read().decode()
AttributeError: 'NoneType' object has no attribute 'read'

2019-07-03 14:54:29,096 0 'NoneType' object has no attribute 'read' <class 'AttributeError'>
2019-07-03 14:54:29,096 0 Browser closed
2019-07-03 14:54:29,096 0 Time elapsed: 0.11781907081604004
```
Try to check if the headless=True and printed if it is true just to be sure of it but it not work!
I read the issues looking for some kind of solution and nothing. Might you help me?

**Comment by skullfrac** [comment]
please refer to the solution at #30
