### ISSUE TITLE
aiohttp

### ISSUE THREAD

**Issue by skullfrac** [mikeyy/nonoCAPTCHA#60]

**Comment by MacKey-255** [comment]
You need update the dependencies

**Comment by singgi11** [comment]
well, I'm having the same error as ts - it just opens the chromium and then it ended with pyppeteer.errors.NetworkError: Request is already handled.

**Comment by Francesco149** [comment]
this happens because there's two request listeners at the same time. merge the block_images listener with the inject_widget one to fix.

**Comment by MacKey-255** [comment]
> well, I'm having the same error as ts - it just opens the chromium and then it ended with pyppeteer.errors.NetworkError: Request is already handled.
Look my fork here [https://github.com/MacKey-255/GoodByeCatpcha](https://github.com/MacKey-255/GoodByeCatpcha)

**Comment by weaming** [comment]
Same issue
```
2020-05-09 15:55:27,559 Exception in callback <function CompatEventEmitter._emit_run.<locals>._callback at 0x7f78198f1158>
handle: <Handle CompatEventEmitter._emit_run.<locals>._callback>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.6/dist-packages/pyee/_compat.py", line 63, in _callback
    self.emit('error', exc)
  File "/usr/local/lib/python3.6/dist-packages/pyee/_base.py", line 111, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/usr/local/lib/python3.6/dist-packages/pyee/_base.py", line 83, in _emit_handle_potential_error
    raise error
  File "/usr/local/lib/python3.6/dist-packages/nonocaptcha/solver.py", line 110, in handle_request
    await request.continue_()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer/network_manager.py", line 483, in continue_
    raise NetworkError('Request is already handled.')
pyppeteer.errors.NetworkError: Request is already handled.
```

How to fix it ? Any one has an PR for this?

**Comment by Francesco149** [comment]
@weaming  https://github.com/Francesco149/nonoCAPTCHA/commit/168c834cbd2612ceb2841a88a56822caf7adba79

**Comment by weaming** [comment]
> @weaming [Francesco149@168c834](https://github.com/Francesco149/nonoCAPTCHA/commit/168c834cbd2612ceb2841a88a56822caf7adba79)

@Francesco149 I'm using your fork repo to test, but an error raised:

```
root@eb0004fc9a4e:/app2/nonoCAPTCHA/examples# python3.6 demo.py
/usr/local/lib/python3.6/dist-packages/nonocaptcha_fork/base.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  settings = yaml.load(f)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nonocaptcha_fork/solver.py", line 64, in start
    self.browser = await self.get_new_browser()
  File "/usr/local/lib/python3.6/dist-packages/nonocaptcha_fork/solver.py", line 179, in get_new_browser
    browser = await self.launcher.launch()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer_fork/launcher.py", line 174, in launch
    self.browserWSEndpoint = self._get_ws_endpoint()
  File "/usr/local/lib/python3.6/dist-packages/pyppeteer_fork/launcher.py", line 211, in _get_ws_endpoint
    with urlopen(url) as f:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1354, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

2020-05-10 05:04:41,638 0 Remote end closed connection without response <class 'http.client.RemoteDisconnected'>
2020-05-10 05:04:41,670 0 Browser closed
2020-05-10 05:04:41,671 0 Time elapsed: 1.2698609828948975
```

As I'm using it in a docker container, I set the headless to true in `nonocaptcha.yaml`.

Do you have any suggestion?
