### ISSUE TITLE
Problem with running

### ISSUE THREAD

**Issue by FabiCrafter** [mikeyy/nonoCAPTCHA#66]
C:\Users\Nutzer\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
C:\Users\Nutzer\AppData\Local\Programs\Python\Python37\lib\site-packages\nonocaptcha-2.0.1-py3.7.egg\nonocaptcha\base.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  settings = yaml.load(f)
C:\Users\Nutzer\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\Nutzer\source\repos\2Captcha\2Captcha\_2Captcha.py", line 2, in <module>
    from nonocaptcha.solver import Solver
  File "C:\Users\Nutzer\AppData\Local\Programs\Python\Python37\lib\site-packages\nonocaptcha-2.0.1-py3.7.egg\nonocaptcha\solver.py", line 17, in <module>
    from nonocaptcha.audio import SolveAudio
  File "C:\Users\Nutzer\AppData\Local\Programs\Python\Python37\lib\site-packages\nonocaptcha-2.0.1-py3.7.egg\nonocaptcha\audio.py", line 14, in <module>
    from nonocaptcha.speech import Amazon, Azure, Sphinx, DeepSpeech, AzureSpeech
  File "C:\Users\Nutzer\AppData\Local\Programs\Python\Python37\lib\site-packages\nonocaptcha-2.0.1-py3.7.egg\nonocaptcha\speech.py", line 21, in <module>
    from pocketsphinx.pocketsphinx import Decoder
  File "C:\Users\Nutzer\AppData\Local\Programs\Python\Python37\lib\site-packages\pocketsphinx-0.1.15-py3.7-win-amd64.egg\pocketsphinx\__init__.py", line 35, in <module>
    from sphinxbase import *
  File "C:\Users\Nutzer\AppData\Local\Programs\Python\Python37\lib\site-packages\pocketsphinx-0.1.15-py3.7-win-amd64.egg\sphinxbase\__init__.py", line 35, in <module>
    from .ad_win32 import *
ModuleNotFoundError: No module named 'sphinxbase.ad_win32'

Can anyone help me? how i can install sphinxbase.ad_win32??

**Comment by FabiCrafter** [comment]
OS : Windows 1809

**Comment by FabiCrafter** [comment]
I tried it on my Debian VM and it's working fine!

**Comment by azamet90** [comment]
same error i do have did you solve it?
